 insert into organisms
 ( scientific_name , common_name , kingdom)
 values
 ('Homo sapiens' , 'Human' , 'Animalia');

 insert into gene
 (gene_name)
 values
 ('TP53'),
 ('BRCA1'),
 ('BRCA2'),
 ('EGFR'),
 ('KRAS'),
 ('HRAS'),
 ('NRAS'),
 ('BRAF'),
 ('PTEN'),
 ('APC'),
 ('RB1'),
 ('MYC'),
 ('PIK3CA'),
 ('ATM'),
 ('CDKN2A'),
 ('MLH1'),
 ('MSH2'),
 ('MSH6'),
 ('PMS2'),
 ('VHL'),
 ('WT1'),
 ('KIT'),
 ('ALK'),
 ('RET'),
 ('MET'),
 ('ERBB2'),
 ('PALB2'),
 ('CHEK2'),
 ('CDH1'),
 ('SMAD4'),
 ('NF1'),
 ('NF2'),
 ('STK11'),
 ('FLCN'),
 ('FH'),
 ('BAP1'),
 ('ARID1A'),
 ('JAK2'),
 ('ABL1');
 
 insert into protein
 (protein_name , protein_size , chromosome)
 values
 ('Cell Tumor Antigen 53' , '53kDa' , '17p13.1' ),
 ('Breast Cancer type 1 susceptibility protien' , '220kDa' , '17q21.31'),
 ('Breast Cancer type 2 susceptibility protien' , '384kDa' , '13q13.1'),
 ('Epidermal growth factor receptor' , '134kDa' , '7p11.2'),
 ('GTPase karse', '21kDa' , '12p12.1'),
 ('GTPase hars' , '21kDa' , '11p15.5'),
 ('GTPase nars' , '21kDa' , '1p13.2'),
 ('Serine/theronine-protien kinase B-Raf' , '84kDa' , '7q34'),
 ('Phosphatidylinositol 3,4,5-triphosphate-3-phosphatase' , '54kDa' , '10q23.31'),
 ('Adenomatous polyposis coli protein' , '312kDa' , '5q22.2'),
 ('Retinoblastoma-associated protein' , '106kDa' , '13q14.2'),
 ('Myc proto-oncogene protein' , '49kDa' , '8q24.21'),
 ('Phosphotidylinositol 4,5-bisphosphate-3-kinase catalytic subunit alpha' , '124kDa' ,'3q26.32'),
 ('Serine-protein kinase ATM' , '350kDa' , '11q22.3'),
 ('Cyclin-dependent kinase inhibitor 2A' , '16kDa' , '9p21.3'),
 ('DNA mismatch repair prorein Mlh1' , '85kDa' , '3p22.2'),
 ('DNA mismatch repair prorein Msh2' , '105kDa' , '2p21-p16.3'),
 ('DNA mismatch repair prorein Msh6' , '160kDa' , '2p16.3'),
 ('Mismatch repair endonucleases PMS2' , '96kDa' , '7p22.1'),
 ('Von Hippel-Lindau disease tumor suppressor' , '24kDa' , '3p25.3'),
 ('Wilms tumor protein' , '49kDa' , '11p13'),
 ('Mast/stem cell growth factor receptor kit' , '110kDa' , '4q12'),
 ('Anaplastic lymphoma kinase' , '177kDa' ,'2p23.2'),
 ('Proto-oncogene tyrosine-protein kinase receptor Ret' , '124kDa' , '10q11.21' ),
 ('Hepatocyte growth factor receptor' , '156kDa' , '7q31.2'),
 ('Receptor tyrosine-protein kinase erbB-2' , '138kDa' , '17q12'),
 ('Partner and Localizer of BRCA2' , '131kDa' , '16p12.2'),
 ('Sereine/theronine-protein kinase Chk2' , '61kDa' , '22q12.1'),
 ('Cadherin-1' , '97kDa' , '16q22.1' ),
 ('Mothers against decapentaplegic homolog 4' , '60kDa' ,'18q21.2'),
 ('Neurofibromin' , '319kDa','17q11.2'),
('Merlin' , '70kDa','22q12.2'),
 ('Sereine/theronine-protein kinase STK11' , '48kDa','19p13.3'),
 ('Foliculin' , '64kDa','17p11.2'),
('Fumarate hydratase, mitochondrial' , '54kDa','1q43' ),
('Ubiquitin carboxyl-terminal hydrolase BAP 1' , '80kDa','3p21.1'),
('AT-rich interactive domain-containing protein 1A' , '242kDa','1p36.11'),
('E3 ubiquitin-protein ligase Mdm2' , '55kDa','12q15'),
('Tyrosine-protein kinase JAK2' , '131kDa','9p24.1'),
('Tyrosine-Protein kinase ABL1' , '126kDa','9q34.12');
 
 
 insert into function_table
 (function_of_protein)
 values
( 'Tumor suppressor / Transcription factor: Regulates target genes involved in cell cycle arrest, DNA repair, and apoptosis in response to cellular stress.'),
( 'DNA repair / E3 ubiquitin ligase: Plays a central role in homologous recombination repair of DNA double-strand breaks and maintaining genomic stability.'),
( 'DNA repair: Recruits and stabilizes the RAD51 recombinase at DNA double-strand breaks to facilitate homologous recombination.'),
( 'Receptor Tyrosine Kinase (RTK): Binds extracellular ligands to initiate intracellular cascades (MAPK, PI3K/Akt) promoting cell proliferation and survival.'),
( 'Small GTPase / Molecular Switch: Transmits upstream signals from RTKs to downstream kinase cascades by cycling between active GTP-bound and inactive GDP-bound states.'),
( 'Small GTPase: Functions similarly to KRAS; transduces growth signals from cell surface receptors to intracellular pathways.'),
( 'Small GTPase: Essential for regular signaling in hematopoietic and melanocytic lineages; activates cell survival and proliferation pathways.'),
( 'Serine/Threonine Kinase: Acts as an intermediate driver in the MAPK/ERK pathway; directly phosphorylates and activates MEK1/2.'),
( 'Dual-specificity Phosphatase: Dephosphorylates PIP3 to PIP2, directly counteracting the PI3K/Akt/mTOR survival pathway to act as a crucial tumor suppressor.'),
( 'Tumor Suppressor: Functions as a core scaffolding component of the beta-catenin destruction complex, negatively regulating the Wnt signaling pathway.'),
( 'Cell Cycle Regulator: In its unphosphorylated state, it binds and represses E2F transcription factors, blocking the G1/S phase cell cycle transition.'),
( 'Transcription Factor: Promotes cell cycle progression, metabolic reprogramming, and protein synthesis by binding E-box elements in DNA.'),
( 'Lipid Kinase: Phosphorylates PIP2 to generate PIP3 at the plasma membrane, driving the activation of Akt downstream of growth factor stimulation.'),
( 'Serine/Threonine Kinase: Acts as a primary sensor of DNA double-strand breaks, phosphorylating TP53, CHK2, and BRCA1 to arrest the cell cycle.'),
( 'CDK Inhibitor: Binds and inactivates CDK4/6, keeping RB1 unphosphorylated and preventing aberrant cell division.'),
( 'Mismatch Repair (MMR) Protein: Forms a heterodimer that helps coordinate the excision and resynthesis of mismatched base pairs during DNA replication.'),
( 'Mismatch Repair Protein: Forms the complexes responsible for the initial recognition of mispaired bases and insertion/deletion loops.'),
( 'Mismatch Repair Protein: Partners with MSH2 to recognize single-base mismatches and short insertion/deletion loops.'),
( 'Mismatch Repair Endonuclease: Partners with MLH1 to introduce a single-strand nick in the nascent DNA strand, guiding error removal.'),
( 'E3 Ubiquitin Ligase Component: Targets Hypoxia-Inducible Factors for proteasomal degradation under normoxic (normal oxygen) conditions.'),
( 'Transcription Factor / RNA Processor: Essential for normal urogenital development; acts as either a transcriptional activator or repressor depending on cellular context.'),
( 'Receptor Tyrosine Kinase: Binds Stem Cell Factor to regulate hematopoiesis, melanogenesis, and the development of interstitial cells of Cajal.'),
( 'Receptor Tyrosine Kinase: Involved in nervous system development; when fused with partner proteins, it displays constitutive kinase activity.'),
( 'Receptor Tyrosine Kinase: Functions as a receptor for glial cell line-derived neurotrophic factor family ligands, critical for neural crest and kidney development.'),
( 'Receptor Tyrosine Kinase: Binds Hepatocyte Growth Factor to signal tissue remodeling, cell epithelial-mesenchymal transition, and cell motility.'),
( 'Orphan Receptor Tyrosine Kinase: Lacks a known direct ligand; instead, it acts as a preferred heterodimerization partner for other EGFR family members to amplify downstream survival signaling.'),
( 'DNA Repair Scaffolding: Bridges BRCA1 and BRCA2 at the site of DNA double-strand breaks, ensuring structural assembly of the repair machinery.'),
( 'Serine/Threonine Kinase: Activated by ATM in response to DNA damage; phosphorylates TP53 and CDC25A to enforce cell cycle arrest.'),
( 'Calcium-Dependent Cell Adhesion Molecule: Establishes epithelial cell-to-cell junctions; loss of function permits cell detachment, invasion, and metastasis.'),
( 'Signal Transducer / Co-SMAD: Acts as the central, common mediator in the TGF-beta signaling pathway, complexing with pathway-specific SMADs to regulate transcription.'),
( 'GTPase-Activating Protein (GAP): Accelerates the hydrolysis of active RAS-GTP to inactive RAS-GDP, acting as a negative regulator of RAS signaling.'),
( 'Cytoskeletal Linker Protein: Links cell membrane proteins to the actin cytoskeleton; mediates contact inhibition through the Hippo signaling pathway.'),
( 'Master Upstream Kinase: Directly phosphorylates and activates AMPK under energy stress, regulating cellular metabolism, polarity, and growth inhibition.'),
( 'GTPase Exchange Regulator: Interacts with Rag GTPases to modulate the mTORC1 signaling pathway, playing a key role in cellular nutrient sensing.'),
( 'TCA Cycle Enzyme: Catalyzes the reversible hydration of fumarate to L-malate. Loss of function drives pseudohypoxia.'),
( 'Deubiquitinating Enzyme (DUB): Cleaves ubiquitin from specific histones, regulating chromatin remodeling, gene expression, and the DNA damage response.'),
( 'Chromatin Remodeling Subunit: Core component of the SWI/SNF complex; helps maintain chromatin structure to regulate access to DNA for transcription and repair.'),
( 'E3 Ubiquitin Ligase: Directly binds p53, targeting it for ubiquitin-mediated proteasomal degradation and keeping p53 levels low in unstressed cells.'),
( 'Non-Receptor Tyrosine Kinase: Mediates signaling from cytokine and growth hormone receptors through the JAK/STAT pathway, controlling hematopoiesis.'),
( 'Non-Receptor Tyrosine Kinase: Involved in cell differentiation, division, and stress responses. When aberrantly fused to partner genes via translocation, it becomes constitutively active.');


insert into disease
(disease_of_protein)
values

( 'Li-Fraumeni syndrome; Osteosarcoma, Breast, Lung, and Colorectal cancers'),
( 'Hereditary Breast and Ovarian Cancer (HBOC) syndrome'),
( 'HBOC syndrome; Pancreatic and Prostate cancers; Fanconi Anemia'),
( 'Non-small cell lung cancer (NSCLC); Glioblastoma'),
( 'Pancreatic, Colorectal, and Non-small cell lung adenocarcinomas'),
( 'Bladder cancer; Costello syndrome'),
( 'Cutaneous Melanoma; Acute Myeloid Leukemia (AML)'),
( 'Melanoma; Colorectal cancer; Papillary thyroid carcinoma'),
( 'Cowden syndrome; Glioblastoma, Prostate, and Endometrial cancers'),
( 'Familial Adenomatous Polyposis (FAP); Colorectal cancer'),
( 'Retinoblastoma; Osteosarcoma; Small cell lung cancer'),
( 'Burkitt lymphoma; Breast, Cervical, and Small cell lung cancers'),
( 'Breast, Colorectal, and Endometrial cancers'),
( 'Ataxia-telangiectasia; T-cell prolymphocytic leukemia; Breast cancer'),
( 'Familial Melanoma; Pancreatic adenocarcinoma'),
( 'Lynch syndrome (Hereditary Non-Polyposis Colorectal Cancer)'),
( 'Lynch syndrome; Muir-Torre syndrome'),
( 'Lynch syndrome; Endometrial carcinoma'),
( 'Lynch syndrome; Constitutional Mismatch Repair Deficiency (CMMRD)'),
( 'Von Hippel-Lindau syndrome; Clear cell renal cell carcinoma'),
( 'Wilms tumor; WAGR syndrome; Denys-Drash syndrome'),
( 'Gastrointestinal Stromal Tumors (GIST); Mast cell leukemia'),
( 'Anaplastic large-cell lymphoma; NSCLC; Neuroblastoma'),
( 'Multiple Endocrine Neoplasia type 2 (MEN2); Medullary thyroid carcinoma'),
( 'Papillary renal cell carcinoma; Gastric and Lung cancers'),
( 'HER2-positive Breast, Gastric, and Ovarian cancers'),
( 'Familial Breast and Pancreatic cancers'),
( 'Li-Fraumeni-like syndrome; Breast and Prostate cancers'),
( 'Hereditary Diffuse Gastric Cancer; Lobular Breast carcinoma'),
( 'Juvenile Polyposis syndrome; Pancreatic adenocarcinoma'),
( 'Neurofibromatosis type 1; Juvenile myelomonocytic leukemia'),
( 'Neurofibromatosis type 2; Schwannomatosis; Meningioma'),
( 'Peutz-Jeghers syndrome; Non-small cell lung carcinoma'),
( 'Birt-Hogg-Dubé syndrome; Renal cell carcinoma'),
( 'Hereditary Leiomyomatosis and Renal Cell Cancer (HLRCC)'),
( 'BAP1 tumor predisposition syndrome; Uveal melanoma; Mesothelioma'),
( 'Ovarian clear cell carcinoma; Gastric and Endometrial cancers'),
( 'Liposarcoma; Osteosarcoma'),
( 'Polycythemia vera; Essential thrombocythemia; Myelofibrosis'),
( 'Chronic Myelogenous Leukemia (CML)');

 INSERT INTO protein_function (protein_id, function_id)
VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5),
(6,6),
(7,7),
(8,8),
(9,9),
(10,10),
(11,11),
(12,12),
(13,13),
(14,14),
(15,15),
(16,16),
(17,17),
(18,18),
(19,19),
(20,20),
(21,21),
(22,22),
(23,23),
(24,24),
(25,25),
(26,26),
(27,27),
(28,28),
(29,29),
(30,30),
(31,31),
(32,32),
(33,33),
(34,34),
(35,35),
(36,36),
(37,37),
(38,38),
(39,39),
(40,40);
 
 
 INSERT INTO protein_disease (protein_id, disease_id)
VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5),
(6,6),
(7,7),
(8,8),
(9,9),
(10,10),
(11,11),
(12,12),
(13,13),
(14,14),
(15,15),
(16,16),
(17,17),
(18,18),
(19,19),
(20,20),
(21,21),
(22,22),
(23,23),
(24,24),
(25,25),
(26,26),
(27,27),
(28,28),
(29,29),
(30,30),
(31,31),
(32,32),
(33,33),
(34,34),
(35,35),
(36,36),
(37,37),
(38,38),
(39,39),
(40,40);